import { execSync } from 'node:child_process'
import { createHash } from 'node:crypto'
import { readFileSync, readdirSync, statSync } from 'node:fs'
import path from 'node:path'

import createMDX from '@next/mdx'
import withSerwistInit from '@serwist/next'
import type { NextConfig } from 'next'

interface PrecacheEntry {
  url: string
  revision: string
}

/**
 * Page URLs to precache, generated by `scripts/precache-routes.ts` before the
 * build. Serwist's own manifest covers webpack assets only, so without these the
 * app would work offline except for every song in it.
 */
function pageEntries(): PrecacheEntry[] {
  let routes: string[]
  try {
    const file = path.join(process.cwd(), 'generated', 'precache-routes.json')
    routes = JSON.parse(readFileSync(file, 'utf8'))
  } catch (error) {
    console.warn(`[precache] could not read the route list, pages will NOT be precached: ${error}`)
    return []
  }

  // One revision for the whole set: any content change means a new build, and
  // every page is regenerated together anyway.
  const revision = process.env.VERCEL_GIT_COMMIT_SHA ?? String(routes.length)
  return routes.map((url) => ({ url, revision }))
}

/**
 * Files in `public/`, hashed — recursively, since `public/brand/` (favicons, PWA
 * icons, lockups, OG image, the email logo) nests them in subfolders rather than
 * leaving everything loose at the root.
 *
 * @serwist/next scans the public folder itself, but *only* when
 * additionalPrecacheEntries is absent — and an empty array is enough to skip it.
 * Since we always pass entries, the scan has to happen here or the icons quietly
 * stop being precached. `readdirSync`'s `recursive` option returns plain relative
 * path strings in `encoding: 'utf8'` mode, not `Dirent`s — deliberately: a
 * `Dirent`'s parent-directory field was `.path` before Node 20.12/18.20 and is
 * `.parentPath` after, so reconstructing a nested path from it would silently
 * differ by Node version. Dot-entries are skipped too, since a local build (unlike
 * Vercel's, which builds from a clean git checkout) can have tool state such as
 * `public/.impeccable/` sitting in the working tree, and nothing but a build
 * artifact belongs in a shipped precache manifest.
 *
 * `public/brand/kit/` is skipped for a different reason: it is the brand asset drop
 * hosted whole, every size of every lockup, so a logo can be fetched by URL when one
 * is needed outside this app. Nothing in the app renders any of it, and it is over ten
 * times the weight of everything else in `public/` put together — precaching it would
 * make every install of the PWA download megabytes of PNGs nobody asked for. The files
 * the app *does* draw live at `brand/` and `brand/icons/` and are still precached, some
 * of them byte-identical to a copy inside the kit.
 */
function publicEntries(): PrecacheEntry[] {
  const publicDir = path.join(process.cwd(), 'public')

  try {
    return readdirSync(publicDir, { recursive: true, encoding: 'utf8' })
      .filter((relativePath) => !relativePath.split(path.sep).some((segment) => segment.startsWith('.')))
      .filter((relativePath) => !/^sw\.js(\.map)?$|^swe-worker-/.test(relativePath))
      .filter((relativePath) => !/^brand[\\/]kit[\\/]/.test(relativePath))
      /*
       * `public/brand/launch/` is skipped for a reason sharper than the kit's: iOS paints the
       * launch screen *before* the service worker exists, so a precached copy could not be the
       * one it uses even in principle. Precaching them would be half a megabyte downloaded on
       * every install to sit unread — see `src/lib/launchScreens.ts` for what they are.
       */
      .filter((relativePath) => !/^brand[\\/]launch[\\/]/.test(relativePath))
      /*
       * `public/blog/` is skipped for the same family of reasons as the two above, arrived at
       * from the marketing side: an article's cover is a 1200×630 picture drawn for a link
       * preview and for a page a *visitor* reads before they have an account, and nothing
       * inside the installed app ever renders one. Precaching them would make every install
       * download the whole archive's artwork — growing with every article published — to show
       * a reader nothing. The blog is kept out of the page precache too, in
       * `scripts/precache-routes.ts`, and out of the runtime caches by `middleware.ts`; this
       * is the third of the three, and the one that would otherwise grow without limit.
       */
      .filter((relativePath) => !/^blog[\\/]/.test(relativePath))
      .filter((relativePath) => statSync(path.join(publicDir, relativePath)).isFile())
      .map((relativePath) => {
        const contents = readFileSync(path.join(publicDir, relativePath))
        return {
          url: `/${relativePath.split(path.sep).join('/')}`,
          revision: createHash('md5').update(contents).digest('hex'),
        }
      })
  } catch {
    return []
  }
}

/**
 * The commit this build was made from, shown in the footer of every internal page.
 *
 * `git rev-parse` first, `VERCEL_GIT_COMMIT_SHA` as a fallback: a CLI deploy
 * (`vercel --prod`) uploads sources without the `.git` directory, so the command fails
 * there, and the env var Vercel injects covers it instead — same fallback order
 * `easy-guitar-tuner`'s `vite.config.js` already uses for the same reason.
 */
function commitHash(): string {
  try {
    return execSync('git rev-parse --short HEAD', { stdio: ['ignore', 'pipe', 'ignore'] })
      .toString()
      .trim()
  } catch {
    return (process.env.VERCEL_GIT_COMMIT_SHA ?? 'dev').slice(0, 7)
  }
}

const nextConfig: NextConfig = {
  /**
   * Inlined at build time wherever `process.env.COMMIT_HASH` is read, in server or
   * client code alike — see `Footer.tsx`, the only reader.
   */
  env: {
    COMMIT_HASH: commitHash(),
  },
  /**
   * The app's routes were renamed from Italian to English (`/canzonieri` →
   * `/songbooks`, and so on). These carry anyone with an old bookmark or a
   * shared link forward instead of a 404.
   */
  async redirects() {
    return [
      { source: '/canzonieri', destination: '/', permanent: true },
      { source: '/canzonieri/:slug', destination: '/songbooks/:slug', permanent: true },
      { source: '/canzoni/:slug', destination: '/songs/:slug', permanent: true },
      { source: '/canzoni/:slug/modifica', destination: '/songs/:slug/edit', permanent: true },
      { source: '/importa', destination: '/', permanent: true },
      /*
       * '/songbooks', '/import' and '/users' were pages of their own — create/rename/
       * remove a songbook, import songs into one, and manage collaborators — folded
       * into the home screen, into each songbook's own page, or removed outright
       * (collaborators, v3.1). Nothing replaces any of them directly, so all three
       * land on '/'; '/canzonieri', '/importa' and '/utenti' above go straight there
       * too, rather than bouncing through the routes they used to become before
       * those were retired.
       */
      { source: '/songbooks', destination: '/', permanent: true },
      { source: '/import', destination: '/', permanent: true },
      { source: '/users', destination: '/', permanent: true },
      { source: '/utenti', destination: '/', permanent: true },
      /*
       * The auth loop's own routes, renamed the same way. `/verifica` and
       * `/reimposta-password` are the two that matter most: both are links already
       * sitting unopened in real inboxes, `?token=` and `?email=` and all — a plain
       * source/destination redirect with no path params forwards the whole query
       * string untouched, so those links keep working rather than 404ing the moment
       * this ships.
       */
      { source: '/registrati', destination: '/register', permanent: true },
      { source: '/password-dimenticata', destination: '/forgot-password', permanent: true },
      { source: '/reimposta-password', destination: '/reset-password', permanent: true },
      { source: '/verifica', destination: '/verify', permanent: true },
    ]
  },
}

/**
 * Teaches the bundler to import an `.mdx` file as a React component — the blog's articles,
 * which live in `content/blog/` and are imported by `lib/blog/posts.ts`.
 *
 * **`pageExtensions` is deliberately left alone.** Adding `mdx` to it is what the @next/mdx
 * README suggests, and it is what makes an `.mdx` file *inside `src/app/` become a route*.
 * Nothing here wants that: the articles are content imported as modules, not pages, and
 * leaving route resolution exactly as it was means no file dropped into the app directory can
 * turn into a URL by accident. What this wrapper is used for is the loader rule alone.
 */
const withMDX = createMDX({})

/*
 * Serwist stays the outer wrapper: it reads the finished config to build the service worker,
 * so anything that adds to the config has to have run by the time it does.
 */
export default withSerwistInit({
  swSrc: 'src/app/sw.ts',
  swDest: 'public/sw.js',
  additionalPrecacheEntries: [...pageEntries(), ...publicEntries()],
  // Only ship a service worker from a real build; in dev it gets in the way.
  disable: process.env.NODE_ENV === 'development',
})(withMDX(nextConfig))
